language: node_js
node_js:
  - "14.10.1"
env:
  - CMD="sass:compile"
  - CMD="lint:sass"
  - CMD="lint:js"
  - CMD="test:karma"
install:
  - "npm install"
script:
  - "npm run $CMD"
addons:
  chrome: stable
